server:
  port: 8081

spring:
  datasource:
    url: ${AIRLINE_CORE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/airline_core_db}
    username: ${AIRLINE_CORE_DATASOURCE_USERNAME:${FLIGHTHUB_DATASOURCE_USERNAME:postgres}}
    password: ${AIRLINE_CORE_DATASOURCE_PASSWORD:${FLIGHTHUB_DATASOURCE_PASSWORD:12345678}}
    driver-class-name: ${AIRLINE_CORE_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

app:
  media-service:
    base-url: ${MEDIA_SERVICE_BASE_URL:http://localhost:8089}
