# =============================================================================
# API GATEWAY CONFIG
# =============================================================================

server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true # Important for CORS to work with Spring Cloud Gateway
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "https://*.vercel.app"
              - "http://localhost:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials