server:
  port: 8083

spring:
  datasource:
    url: ${BOOKING_DATASOURCE_URL}
    username: ${BOOKING_DATASOURCE_USERNAME:${FLIGHTHUB_DATASOURCE_USERNAME}}
    password: ${BOOKING_DATASOURCE_PASSWORD:${FLIGHTHUB_DATASOURCE_PASSWORD}}
    driver-class-name: ${BOOKING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
