server:
  port: 8085

spring:
  datasource:
    url: ${LOCATION_DATASOURCE_URL:jdbc:postgresql://localhost:5432/airline_location_db}
    username: ${LOCATION_DATASOURCE_USERNAME:${FLIGHTHUB_DATASOURCE_USERNAME:postgres}}
    password: ${LOCATION_DATASOURCE_PASSWORD:${FLIGHTHUB_DATASOURCE_PASSWORD:12345678}}
    driver-class-name: ${LOCATION_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
