server:
  port: 8086

spring:
  datasource:
    url: ${PAYMENT_DATASOURCE_URL}
    username: ${PAYMENT_DATASOURCE_USERNAME:${FLIGHTHUB_DATASOURCE_USERNAME}}
    password: ${PAYMENT_DATASOURCE_PASSWORD:${FLIGHTHUB_DATASOURCE_PASSWORD}}
    driver-class-name: ${PAYMENT_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  kafka:
    bootstrap-servers: ${PAYMENT_KAFKA_BOOTSTRAP_SERVERS:${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

payment:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:}
  paypal:
    client-id: ${PAYPAL_CLIENT_ID:}
    client-secret: ${PAYPAL_CLIENT_SECRET:}
    base-url: ${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}

kafka:
  topics:
    payment-completed: ${KAFKA_TOPIC_PAYMENT_COMPLETED:payment.completed}
    payment-failed: ${KAFKA_TOPIC_PAYMENT_FAILED:payment.failed}
