server:
  port: 8087

spring:
  datasource:
    url: ${PRICING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/airline_pricing_db}
    username: ${PRICING_DATASOURCE_USERNAME:${FLIGHTHUB_DATASOURCE_USERNAME:postgres}}
    password: ${PRICING_DATASOURCE_PASSWORD:${FLIGHTHUB_DATASOURCE_PASSWORD:12345678}}
    driver-class-name: ${PRICING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
