server:
  port: 8088

spring:
  datasource:
    # NEON POSTGRESQL (PRODUCTION / CLOUD)
    url: jdbc:postgresql://ep-silent-darkness-aoh21u1p-pooler.c-2.ap-southeast-1.aws.neon.tech/airline_seat_db?sslmode=require
    username: neondb_owner
    password: npg_FDqZpbe3Oml7
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: seat-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.triquang.message