server:
  port: 8089

spring:
  datasource:
    url: ${SUBSCRIPTION_DATASOURCE_URL}
    username: ${SUBSCRIPTION_DATASOURCE_USERNAME:${FLIGHTHUB_DATASOURCE_USERNAME}}
    password: ${SUBSCRIPTION_DATASOURCE_PASSWORD:${FLIGHTHUB_DATASOURCE_PASSWORD}}
    driver-class-name: ${SUBSCRIPTION_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
