server:
  port: 8090

spring:
  datasource:
    url: ${USER_DATASOURCE_URL}
    username: ${USER_DATASOURCE_USERNAME:${FLIGHTHUB_DATASOURCE_USERNAME}}
    password: ${USER_DATASOURCE_PASSWORD:${FLIGHTHUB_DATASOURCE_PASSWORD}}
    driver-class-name: ${USER_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
